# Generated by Django 6.0.3 on 2026-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suitable_face_shapes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
