# Generated by Django 6.0.3 on 2026-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Prescription', max_length=100)),
                ('right_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_pd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_pd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pd_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
    ]
